/* Autogenerated or extracted CFML tags database */
#pragma once

static const cfml_attribute_info cfloop_index_attrs[] = {
    {"index", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {"from", true, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"to", true, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"step", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_cond_attrs[] = {
    {"condition", true, CFML_ATTR_TYPE_ANY, nullptr, CFML_MASK_EXPRESSION},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_query_attrs[] = {
    {"query", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"startrow", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"endrow", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"group", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"groupcasesensitive", false, CFML_ATTR_TYPE_BOOLEAN, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_list_attrs[] = {
    {"list", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"index", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {"delimiters", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_array_attrs[] = {
    {"array", true, CFML_ATTR_TYPE_ANY, nullptr, CFML_MASK_ALL},
    {"index", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {"item", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_collection_attrs[] = {
    {"collection", true, CFML_ATTR_TYPE_ANY, nullptr, CFML_MASK_ALL},
    {"item", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {"index", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_info cfloop_file_attrs[] = {
    {"file", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"index", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_VARIABLE},
    {"charset", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"characters", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_combo cfloop_combos[] = {
    {cfloop_index_attrs},
    {cfloop_cond_attrs},
    {cfloop_query_attrs},
    {cfloop_list_attrs},
    {cfloop_array_attrs},
    {cfloop_collection_attrs},
    {cfloop_file_attrs},
    {nullptr}
};

static const cfml_attribute_info cfabort_attrs[] = {
    {"showerror", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_combo cfabort_combos[] = {
    {cfabort_attrs},
    {nullptr}
};

static const cfml_attribute_info cfinclude_attrs[] = {
    {"template", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"runonce", false, CFML_ATTR_TYPE_BOOLEAN, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_combo cfinclude_combos[] = {
    {cfinclude_attrs},
    {nullptr}
};

static const cfml_attribute_info cfparam_attrs[] = {
    {"name", true, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"type", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"default", false, CFML_ATTR_TYPE_ANY, nullptr, CFML_MASK_ALL},
    {"max", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"min", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"pattern", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_combo cfparam_combos[] = {
    {cfparam_attrs},
    {nullptr}
};

static const cfml_attribute_info cfmail_attrs[] = {
    {"to", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"from", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"subject", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"cc", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"bcc", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"type", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"charset", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"server", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"port", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {"username", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"password", false, CFML_ATTR_TYPE_STRING, nullptr, CFML_MASK_ALL},
    {"timeout", false, CFML_ATTR_TYPE_NUMBER, nullptr, CFML_MASK_ALL},
    {nullptr, false, CFML_ATTR_TYPE_ANY, nullptr, 0}
};

static const cfml_attribute_combo cfmail_combos[] = {
    {cfmail_attrs},
    {nullptr}
};

const cfml_tag_info cfml_tags[] = {
    {"cf_socialplugin", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfabort", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, cfabort_combos},
    {"cfadmin", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfajaximport", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfajaxproxy", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfapplet", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfapplication", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfargument", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfassociate", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfauthenticate", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfbreak", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfcache", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcalendar", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcase", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcatch", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfchart", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfchartdata", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfchartseries", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfchartset", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfclient", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfclientsettings", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcol", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcollection", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcomponent", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcontent", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfcontinue", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfcookie", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdbinfo", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdefaultcase", CFML_END_TAG_REQUIRED, CFML_PARAMS_NONE, nullptr},
    {"cfdirectory", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdiv", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdocument", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdocumentitem", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdocumentsection", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfdump", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfelse", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfelseif", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_EXPRESSION, nullptr},
    {"cferror", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangecalendar", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangeconnection", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangecontact", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangeconversation", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangefilter", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangefolder", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangemail", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexchangetask", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexecute", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfexit", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cffeed", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cffile", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cffileupload", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cffinally", CFML_END_TAG_REQUIRED, CFML_PARAMS_NONE, nullptr},
    {"cfflush", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfform", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfformgroup", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfformitem", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfforward", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfftp", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cffunction", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgraph", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgraphdata", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgrid", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgridcolumn", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgridrow", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfgridupdate", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfheader", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhtmlbody", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhtmlhead", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhtmltopdf", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhtmltopdfitem", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhttp", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfhttpparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfif", CFML_END_TAG_REQUIRED, CFML_PARAMS_EXPRESSION, nullptr},
    {"cfimage", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfimap", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfimapfilter", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfimpersonate", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfimport", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinclude", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, cfinclude_combos},
    {"cfindex", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinput", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinsert", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinterface", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinvoke", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfinvokeargument", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfjava", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflayout", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflayoutarea", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfldap", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflocation", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflock", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflog", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflogin", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfloginuser", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cflogout", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfloop", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, cfloop_combos},
    {"cfmail", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, cfmail_combos},
    {"cfmailparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmailpart", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmap", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmapitem", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmediaplayer", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmenu", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmenuitem", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmessagebox", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfmodule", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfntauthenticate", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfoauth", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfobject", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfobjectcache", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfoutput", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpageencoding", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, cfparam_combos},
    {"cfpdf", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpdfform", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpdfformparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpdfparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpdfsubform", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpod", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpop", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpresentation", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpresentationslide", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfpresenter", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfprint", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfprocessingdirective", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfprocparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfprocresult", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfprogressbar", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfproperty", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfquery", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfqueryparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfregistry", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfreport", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfreportparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfrethrow", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfretry", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_NONE, nullptr},
    {"cfreturn", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_EXPRESSION, nullptr},
    {"cfsavecontent", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfschedule", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfscript", CFML_END_TAG_REQUIRED, CFML_PARAMS_NONE, nullptr},
    {"cfsearch", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfselect", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfservlet", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfservletparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfset", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_EXPRESSION, nullptr},
    {"cfsetting", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfsharepoint", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfsilent", CFML_END_TAG_REQUIRED, CFML_PARAMS_NONE, nullptr},
    {"cfsleep", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfslider", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfspreadsheet", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfsprydataset", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfstopwatch", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfstoredproc", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfswitch", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftable", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftextarea", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftextinput", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfthread", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfthrow", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftimer", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftooltip", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftrace", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftransaction", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftree", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftreeitem", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cftry", CFML_END_TAG_REQUIRED, CFML_PARAMS_NONE, nullptr},
    {"cfupdate", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfwddx", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfwebsocket", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfwhile", CFML_END_TAG_REQUIRED, CFML_PARAMS_EXPRESSION, nullptr},
    {"cfwindow", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfxml", CFML_END_TAG_REQUIRED, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfzip", CFML_END_TAG_OPTIONAL, CFML_PARAMS_KEY_VALUE, nullptr},
    {"cfzipparam", CFML_END_TAG_FORBIDDEN, CFML_PARAMS_KEY_VALUE, nullptr}
};
const int cfml_tag_count = sizeof(cfml_tags) / sizeof(cfml_tags[0]);
