/* Autogenerated HTML tags and attributes database */
#pragma once

#include "html_common.h"
#include <stddef.h>

static const char *const html_global_attributes[] = {
    "accesskey",
    "aria-activedescendant",
    "aria-atomic",
    "aria-autocomplete",
    "aria-busy",
    "aria-checked",
    "aria-colcount",
    "aria-colindex",
    "aria-colspan",
    "aria-controls",
    "aria-current",
    "aria-describedby",
    "aria-disabled",
    "aria-dropeffect",
    "aria-errormessage",
    "aria-expanded",
    "aria-flowto",
    "aria-grabbed",
    "aria-haspopup",
    "aria-hidden",
    "aria-invalid",
    "aria-label",
    "aria-labelledby",
    "aria-level",
    "aria-live",
    "aria-modal",
    "aria-multiline",
    "aria-multiselectable",
    "aria-orientation",
    "aria-owns",
    "aria-placeholder",
    "aria-posinset",
    "aria-pressed",
    "aria-readonly",
    "aria-relevant",
    "aria-required",
    "aria-roledescription",
    "aria-rowcount",
    "aria-rowindex",
    "aria-rowspan",
    "aria-selected",
    "aria-setsize",
    "aria-sort",
    "aria-valuemax",
    "aria-valuemin",
    "aria-valuenow",
    "aria-valuetext",
    "autocapitalize",
    "autocorrect",
    "autofocus",
    "class",
    "contenteditable",
    "contextmenu",
    "dir",
    "draggable",
    "dropzone",
    "enterkeyhint",
    "exportparts",
    "hidden",
    "id",
    "inert",
    "inputmode",
    "is",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "lang",
    "nonce",
    "onabort",
    "onafterprint",
    "onanimationend",
    "onanimationiteration",
    "onanimationstart",
    "onappinstalled",
    "onaudioend",
    "onaudioprocess",
    "onaudiostart",
    "onbeforeprint",
    "onbeforeunload",
    "onbeginevent",
    "onblocked",
    "onblur",
    "onboundary",
    "oncached",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onchargingchange",
    "onchargingtimechange",
    "onchecking",
    "onclick",
    "onclose",
    "oncomplete",
    "oncompositionend",
    "oncompositionstart",
    "oncompositionupdate",
    "oncontextmenu",
    "oncopy",
    "oncut",
    "ondblclick",
    "ondevicechange",
    "ondevicelight",
    "ondevicemotion",
    "ondeviceorientation",
    "ondeviceproximity",
    "ondischargingtimechange",
    "ondomactivate",
    "ondomattributenamechanged",
    "ondomattrmodified",
    "ondomcharacterdatamodified",
    "ondomcontentloaded",
    "ondomelementnamechanged",
    "ondomfocusin",
    "ondomfocusout",
    "ondomnodeinserted",
    "ondomnodeinsertedintodocument",
    "ondomnoderemoved",
    "ondomnoderemovedfromdocument",
    "ondomsubtreemodified",
    "ondownloading",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onend",
    "onended",
    "onendevent",
    "onerror",
    "onfocus",
    "onfocusin",
    "onfocusout",
    "onformchange",
    "onforminput",
    "onfullscreenchange",
    "onfullscreenerror",
    "ongamepadconnected",
    "ongamepaddisconnected",
    "ongotpointercapture",
    "onhashchange",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeypress",
    "onkeyup",
    "onlanguagechange",
    "onlevelchange",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadend",
    "onloadstart",
    "onlostpointercapture",
    "onmark",
    "onmessage",
    "onmessageerror",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmousewheel",
    "onnomatch",
    "onnotificationclick",
    "onnoupdate",
    "onobsolete",
    "onoffline",
    "ononline",
    "onopen",
    "onorientationchange",
    "onpagehide",
    "onpageshow",
    "onpaste",
    "onpause",
    "onplay",
    "onplaying",
    "onpointercancel",
    "onpointerdown",
    "onpointerenter",
    "onpointerleave",
    "onpointerlockchange",
    "onpointerlockerror",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointerup",
    "onpopstate",
    "onprogress",
    "onpush",
    "onpushsubscriptionchange",
    "onratechange",
    "onreadystatechange",
    "onrepeatevent",
    "onreset",
    "onresize",
    "onresourcetimingbufferfull",
    "onresult",
    "onresume",
    "onscroll",
    "onseeked",
    "onseeking",
    "onselect",
    "onselectionchange",
    "onselectstart",
    "onshow",
    "onslotchange",
    "onsoundend",
    "onsoundstart",
    "onspeechend",
    "onspeechstart",
    "onstalled",
    "onstart",
    "onstorage",
    "onsubmit",
    "onsuccess",
    "onsuspend",
    "onsvgabort",
    "onsvgerror",
    "onsvgload",
    "onsvgresize",
    "onsvgscroll",
    "onsvgunload",
    "onsvgzoom",
    "ontimeout",
    "ontimeupdate",
    "ontouchcancel",
    "ontouchend",
    "ontouchmove",
    "ontouchstart",
    "ontransitionend",
    "onunload",
    "onupdateready",
    "onupgradeneeded",
    "onuserproximity",
    "onversionchange",
    "onvisibilitychange",
    "onvoiceschanged",
    "onvolumechange",
    "onwaiting",
    "onwheel",
    "part",
    "popover",
    "role",
    "slot",
    "spellcheck",
    "style",
    "tabindex",
    "title",
    "translate",
    "virtualkeyboardpolicy",
};
static const int html_global_attribute_count = sizeof(html_global_attributes) / sizeof(html_global_attributes[0]);

static const char *const html_void_elements[] = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
};
static const int html_void_element_count = sizeof(html_void_elements) / sizeof(html_void_elements[0]);

static const char *const tag_attrs_a[] = {
    "download",
    "href",
    "hreflang",
    "ping",
    "rel",
    "target",
    "type",
};

static const char *const tag_attrs_area[] = {
    "alt",
    "coords",
    "download",
    "href",
    "hreflang",
    "ping",
    "rel",
    "shape",
    "target",
    "type",
};

static const char *const tag_attrs_audio[] = {
    "autoplay",
    "controls",
    "crossorigin",
    "loop",
    "mediagroup",
    "muted",
    "preload",
    "src",
};

static const char *const tag_attrs_base[] = {
    "href",
    "target",
};

static const char *const tag_attrs_blockquote[] = {
    "cite",
};

static const char *const tag_attrs_body[] = {
    "onafterprint",
    "onbeforeprint",
    "onbeforeunload",
    "onhashchange",
    "onlanguagechange",
    "onmessage",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpageshow",
    "onpopstate",
    "onstorage",
    "onunload",
};

static const char *const tag_attrs_button[] = {
    "autofocus",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "name",
    "popovertarget",
    "popovertargetaction",
    "type",
    "value",
};

static const char *const tag_attrs_canvas[] = {
    "height",
    "width",
};

static const char *const tag_attrs_col[] = {
    "span",
};

static const char *const tag_attrs_colgroup[] = {
    "span",
};

static const char *const tag_attrs_data[] = {
    "value",
};

static const char *const tag_attrs_del[] = {
    "cite",
    "datetime",
};

static const char *const tag_attrs_details[] = {
    "name",
    "open",
};

static const char *const tag_attrs_embed[] = {
    "height",
    "src",
    "type",
    "width",
};

static const char *const tag_attrs_fencedframe[] = {
    "allow",
    "height",
    "width",
};

static const char *const tag_attrs_fieldset[] = {
    "disabled",
    "form",
    "name",
};

static const char *const tag_attrs_form[] = {
    "accept-charset",
    "action",
    "autocomplete",
    "enctype",
    "method",
    "name",
    "novalidate",
    "target",
};

static const char *const tag_attrs_html[] = {
    "manifest",
};

static const char *const tag_attrs_iframe[] = {
    "allowfullscreen",
    "height",
    "name",
    "sandbox",
    "seamless",
    "src",
    "srcdoc",
    "width",
};

static const char *const tag_attrs_img[] = {
    "alt",
    "crossorigin",
    "decoding",
    "fetchpriority",
    "height",
    "ismap",
    "loading",
    "referrerpolicy",
    "sizes",
    "src",
    "srcset",
    "usemap",
    "width",
};

static const char *const tag_attrs_input[] = {
    "accept",
    "alt",
    "autocomplete",
    "autofocus",
    "checked",
    "dirname",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "height",
    "inputmode",
    "list",
    "max",
    "maxlength",
    "min",
    "minlength",
    "multiple",
    "name",
    "pattern",
    "placeholder",
    "popovertarget",
    "popovertargetaction",
    "readonly",
    "required",
    "size",
    "src",
    "step",
    "type",
    "value",
    "width",
};

static const char *const tag_attrs_label[] = {
    "for",
    "form",
};

static const char *const tag_attrs_li[] = {
    "value",
};

static const char *const tag_attrs_link[] = {
    "crossorigin",
    "href",
    "hreflang",
    "media",
    "rel",
    "sizes",
    "type",
};

static const char *const tag_attrs_map[] = {
    "name",
};

static const char *const tag_attrs_meta[] = {
    "charset",
    "content",
    "http-equiv",
    "name",
};

static const char *const tag_attrs_meter[] = {
    "high",
    "low",
    "max",
    "min",
    "optimum",
    "value",
};

static const char *const tag_attrs_object[] = {
    "data",
    "form",
    "height",
    "name",
    "type",
    "typemustmatch",
    "usemap",
    "width",
};

static const char *const tag_attrs_ol[] = {
    "reversed",
    "start",
    "type",
};

static const char *const tag_attrs_optgroup[] = {
    "disabled",
    "label",
};

static const char *const tag_attrs_option[] = {
    "disabled",
    "label",
    "selected",
    "value",
};

static const char *const tag_attrs_output[] = {
    "for",
    "form",
    "name",
};

static const char *const tag_attrs_param[] = {
    "name",
    "value",
};

static const char *const tag_attrs_progress[] = {
    "max",
    "value",
};

static const char *const tag_attrs_q[] = {
    "cite",
};

static const char *const tag_attrs_script[] = {
    "async",
    "charset",
    "crossorigin",
    "defer",
    "nonce",
    "src",
    "type",
};

static const char *const tag_attrs_select[] = {
    "autocomplete",
    "autofocus",
    "disabled",
    "form",
    "multiple",
    "name",
    "required",
    "size",
};

static const char *const tag_attrs_slot[] = {
    "name",
};

static const char *const tag_attrs_source[] = {
    "src",
    "type",
};

static const char *const tag_attrs_style[] = {
    "media",
    "nonce",
    "scoped",
    "type",
};

static const char *const tag_attrs_table[] = {
    "border",
};

static const char *const tag_attrs_td[] = {
    "colspan",
    "headers",
    "rowspan",
};

static const char *const tag_attrs_textarea[] = {
    "autocomplete",
    "autofocus",
    "cols",
    "dirname",
    "disabled",
    "form",
    "inputmode",
    "maxlength",
    "minlength",
    "name",
    "placeholder",
    "readonly",
    "required",
    "rows",
    "wrap",
};

static const char *const tag_attrs_th[] = {
    "abbr",
    "colspan",
    "headers",
    "rowspan",
    "scope",
    "sorted",
};

static const char *const tag_attrs_time[] = {
    "datetime",
};

static const char *const tag_attrs_track[] = {
    "default",
    "kind",
    "label",
    "src",
    "srclang",
};

static const char *const tag_attrs_video[] = {
    "autoplay",
    "controls",
    "crossorigin",
    "height",
    "loop",
    "mediagroup",
    "muted",
    "poster",
    "preload",
    "src",
    "width",
};

static const html_tag_info html_tags[] = {
    {"a", tag_attrs_a, 7},
    {"abbr", NULL, 0},
    {"address", NULL, 0},
    {"area", tag_attrs_area, 10},
    {"article", NULL, 0},
    {"aside", NULL, 0},
    {"audio", tag_attrs_audio, 8},
    {"b", NULL, 0},
    {"base", tag_attrs_base, 2},
    {"bdi", NULL, 0},
    {"bdo", NULL, 0},
    {"blockquote", tag_attrs_blockquote, 1},
    {"body", tag_attrs_body, 13},
    {"br", NULL, 0},
    {"button", tag_attrs_button, 13},
    {"canvas", tag_attrs_canvas, 2},
    {"caption", NULL, 0},
    {"cite", NULL, 0},
    {"code", NULL, 0},
    {"col", tag_attrs_col, 1},
    {"colgroup", tag_attrs_colgroup, 1},
    {"data", tag_attrs_data, 1},
    {"datalist", NULL, 0},
    {"dd", NULL, 0},
    {"del", tag_attrs_del, 2},
    {"details", tag_attrs_details, 2},
    {"dfn", NULL, 0},
    {"dialog", NULL, 0},
    {"div", NULL, 0},
    {"dl", NULL, 0},
    {"dt", NULL, 0},
    {"em", NULL, 0},
    {"embed", tag_attrs_embed, 4},
    {"fencedframe", tag_attrs_fencedframe, 3},
    {"fieldset", tag_attrs_fieldset, 3},
    {"figcaption", NULL, 0},
    {"figure", NULL, 0},
    {"footer", NULL, 0},
    {"form", tag_attrs_form, 8},
    {"h1", NULL, 0},
    {"h2", NULL, 0},
    {"h3", NULL, 0},
    {"h4", NULL, 0},
    {"h5", NULL, 0},
    {"h6", NULL, 0},
    {"head", NULL, 0},
    {"header", NULL, 0},
    {"hgroup", NULL, 0},
    {"hr", NULL, 0},
    {"html", tag_attrs_html, 1},
    {"i", NULL, 0},
    {"iframe", tag_attrs_iframe, 8},
    {"img", tag_attrs_img, 13},
    {"input", tag_attrs_input, 34},
    {"ins", NULL, 0},
    {"kbd", NULL, 0},
    {"label", tag_attrs_label, 2},
    {"legend", NULL, 0},
    {"li", tag_attrs_li, 1},
    {"link", tag_attrs_link, 7},
    {"main", NULL, 0},
    {"map", tag_attrs_map, 1},
    {"mark", NULL, 0},
    {"menu", NULL, 0},
    {"meta", tag_attrs_meta, 4},
    {"meter", tag_attrs_meter, 6},
    {"nav", NULL, 0},
    {"noscript", NULL, 0},
    {"object", tag_attrs_object, 8},
    {"ol", tag_attrs_ol, 3},
    {"optgroup", tag_attrs_optgroup, 2},
    {"option", tag_attrs_option, 4},
    {"output", tag_attrs_output, 3},
    {"p", NULL, 0},
    {"param", tag_attrs_param, 2},
    {"picture", NULL, 0},
    {"pre", NULL, 0},
    {"progress", tag_attrs_progress, 2},
    {"q", tag_attrs_q, 1},
    {"rb", NULL, 0},
    {"rp", NULL, 0},
    {"rt", NULL, 0},
    {"ruby", NULL, 0},
    {"s", NULL, 0},
    {"samp", NULL, 0},
    {"script", tag_attrs_script, 7},
    {"search", NULL, 0},
    {"section", NULL, 0},
    {"select", tag_attrs_select, 8},
    {"selectedcontent", NULL, 0},
    {"slot", tag_attrs_slot, 1},
    {"small", NULL, 0},
    {"source", tag_attrs_source, 2},
    {"span", NULL, 0},
    {"strong", NULL, 0},
    {"style", tag_attrs_style, 4},
    {"sub", NULL, 0},
    {"summary", NULL, 0},
    {"sup", NULL, 0},
    {"table", tag_attrs_table, 1},
    {"tbody", NULL, 0},
    {"td", tag_attrs_td, 3},
    {"template", NULL, 0},
    {"textarea", tag_attrs_textarea, 15},
    {"tfoot", NULL, 0},
    {"th", tag_attrs_th, 6},
    {"thead", NULL, 0},
    {"time", tag_attrs_time, 1},
    {"title", NULL, 0},
    {"tr", NULL, 0},
    {"track", tag_attrs_track, 5},
    {"u", NULL, 0},
    {"ul", NULL, 0},
    {"var", NULL, 0},
    {"video", tag_attrs_video, 11},
    {"wbr", NULL, 0},
};
static const int html_tag_count = sizeof(html_tags) / sizeof(html_tags[0]);
